# Generated by Django 2.0.dev20170317160306 on 2017-03-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20170325_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistes',
            name='spectacles',
        ),
        migrations.AddField(
            model_name='spectacles',
            name='artistes',
            field=models.ManyToManyField(to='polls.Artistes'),
        ),
    ]
