# Generated by Django 2.0.dev20170317160306 on 2017-03-29 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20170325_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistes',
            name='pictures',
            field=models.ImageField(upload_to='artistes/'),
        ),
        migrations.AlterField(
            model_name='spectacles',
            name='pictures',
            field=models.ImageField(upload_to='spectacles/'),
        ),
    ]
