# Generated by Django 2.0.dev20170317160306 on 2017-03-29 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20170329_1127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artistes',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='artistes',
            name='last_name',
        ),
    ]
