# Generated by Django 2.0.dev20170317160306 on 2017-03-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20170329_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spectacles',
            name='artistes',
            field=models.ManyToManyField(blank='true', to='polls.Artistes'),
        ),
    ]
