# Generated by Django 2.0.dev20170317160306 on 2017-03-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20170329_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spectacles',
            name='date',
            field=models.DateField(blank='True', null='True'),
        ),
    ]
