# Generated by Django 2.0.dev20170317160306 on 2017-04-01 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_remove_spectacles_pictures'),
    ]

    operations = [
        migrations.AddField(
            model_name='spectacles',
            name='pictures',
            field=models.CharField(default='static', max_length=100),
        ),
    ]
