# Generated by Django 2.0.dev20170317160306 on 2017-04-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_spectacles_pictures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spectacles',
            name='pictures',
            field=models.ImageField(default='', upload_to='static/'),
        ),
    ]
