# Generated by Django 2.0.dev20170317160306 on 2017-04-01 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_auto_20170401_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spectacles',
            name='pictures',
            field=models.CharField(default='', max_length=100),
        ),
    ]
