# Generated by Django 2.0.dev20170402012442 on 2017-04-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20170403_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='spectacles',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='artistes',
            name='pictures',
            field=models.ImageField(blank='True', null='True', upload_to='artistes/'),
        ),
    ]
