# Generated by Django 2.0.dev20170317160306 on 2017-04-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_auto_20170426_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='tx',
            field=models.IntegerField(),
        ),
    ]
