# Generated by Django 2.0.dev20170317160306 on 2017-04-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_auto_20170426_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='Spectacles',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchaser',
            field=models.IntegerField(),
        ),
    ]
