# Generated by Django 2.0.dev20170317160306 on 2017-04-26 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_auto_20170426_1231'),
    ]

    operations = [
    ]
