# Generated by Django 2.0.dev20170421140231 on 2017-04-27 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_auto_20170426_1248'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
